config/routes.rb
HacketyHackCom::Application.routes.draw do

  get "users/index"

  match 'mailer' => 'mailer#new', :as => 'mailer', :via => :get
  match 'mailer' => 'mailer#create', :as => 'mailer', :via => :post
  get 'users/deleted_user', :to => 'users#deleted_user'

  resources :lessons, :only => [:index, :show]

  resources :questions do
    resources :answers
  end

  resources :blog, :controller => "blog" do
    match "admin", :on => :collection, :controller => "blog", :action => "admin"
  end

  get "/downloads/latest/:platform", :to => "static#download", :as => 'downloads'
  get "/downloads/latest", :to => "static#download", :as => 'download'
  match "/download" => redirect("/downloads/latest")

  scope '/support', :as => 'support' do
    resources :questions, :controller => 'questions' do
      resources :answers
    end
  end

  constraints(ApiConstraint) do
    match '/' => 'static#api_root'
    match '/versions/newest' => 'static#newest_version', :as => "newest_version"
    scope :module => "Api" do
      resources :rels, :only => [:index, :show]
        resources :programs
    end
  end

  resources :programs, :only => [:index, :show]

  devise_for :users
  devise_scope :user do
    get "login" => "devise/sessions#new", :as => "login"
    get "logout" => "devise/sessions#destroy", :as => "logout"
  end

  resources :users, :constraints => { :id => /.*/ }, :only => :show do
    get "following" => "users#following", :as => :following
    get "followers" => "users#followers", :as => :followers
    post "follow" => "users#follow", :as => :follow
    post "unfollow" => "users#unfollow", :as => :unfollow

    resources :programs
  end

  # match ':user_id/:slug', :to => "programs#show", :as => :program

  match 'faq' => 'static#faq'
  root :to => "static#root"

end

app/models/user.rb
class User
  include MongoMapper::Document
  #****many :authentications
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable, 
         :omniauthable, :recoverable, :rememberable, :trackable, :validatable

  many :authentications #*****Trying this thru Line 12 JFTFOI 

  #field :name, :type => String
  #field :provider, :type => String

  validates_uniqueness_of :email #****Trying this thru Line 52 JFTFOI
  #attr_accessible :email, :password, :password_comfirmation, :remember_me, :username

  attr_protected :uid, :name, :email
  #index({email: 1}, {background: true,  unique: true})
  #index({"authentications.provider" => 1}, {background: true})
  #index({"authentications.uid" => 1}, {background: true})
  def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth['provider']
    user.uid = auth['uid']
    if auth['info']
       user.name = auth['info']['name'] || ""
       user.email = auth['info']['email'] || ""
    end
  end
end
  def self.new_with_session(params, session) ## When Omniauth is generating user data, this methid is requested
    if session["devise.user_attributes"]
      auth = session["devise.user_attributes"]
      new do |user|
        user.name = auth['info']['name'] unless auth['info']['name'].blank?
        user.name ||= auth['info']['nickname'] unless auth['info']['nickname'].blank?
        user.name ||= auth['info']['first_name'] + ''+ auth['info']['last_name'] unless auth['info']['first_name'].blank? || auth['last_name'].blank?

        user.email = auth['info']['email'] unless auth['info']['email'].blank?

        user.provider = auth['provider']

        #This password stuff is a complete hack (Lines 33-36)
        user.password, user.password_comfirmation =alid auth['credentials']['token']
        user.valid?
      end
    else
      super
    end

    def pasword_required?
      super && provider.blank?
    end

    def update_with_password(params, *options)
      if encrypted_password.blank?
        update_attributes(params, *options)
      else
        super
      end
    end
  end

  validates_presence_of :username
  validates_uniqueness_of :username
  
  key :username, String
  key :email, String
  key :about, String
  key :moderator, Boolean
  key :blog_poster, Boolean
  
  ## Omniauthable
  key :provider, String
  key :uid,      String
  

   ## Database authenticatable
  key :email,              :type => String, :null => false
  key :encrypted_password, :type => String, :null => false

  ## Recoverable
  key :reset_password_token,   :type => String
  key :reset_password_sent_at, :type => Time

  ## Rememberable
  key :remember_created_at, :type => Time

  ## Trackable
  key :sign_in_count,      :type => Integer
  key :current_sign_in_at, :type => Time
  key :last_sign_in_at,    :type => Time
  key :current_sign_in_ip, :type => String
  key :last_sign_in_ip,    :type => String

  many :questions
  many :answers

  validates_format_of :username, :with => /^[\w\.]+$/,
    :message => "Make your username from letters, numbers, underscores('_'), and dots('.')."
  validates_length_of :username, :in => (1..32),
    :message => "Your username needs at least 1 character but no more than 32."
  validates_uniqueness_of :username,
    :message => "User name has been taken already. Please try another"

  def to_param
    self.username
  end

  def programs
    Program.by_username self.username
  end

  #the list of hackers this hacker is following
  key :following_ids, Array
  many :following, :in => :following_ids, :class_name => 'User'

  #the list of hackers that are following this hacker
  key :followers_ids, Array
  many :followers, :in => :followers_ids, :class_name => 'User'

  #after we create a hacker, we want to have them follow steve, and vice versa!
  after_create :follow_steve

  # this method makes the hacker follow the followee
  def follow! followee
    return if following? followee
    following << followee
    save
    followee.followers << self
    followee.save
  end

  # this method makes the hacker unfollow the followee
  def unfollow! followee
    return if !following? followee
    following_ids.delete(followee.id)
    save
    followee.followers_ids.delete(id)
    followee.save
  end

  # this method returns true if we're following the given Hacker, and
  # false otherwise
  def following? hacker
    following.include? hacker
  end

  # Everyone should have at least one follower. And steve would like to follow
  # everyone. So let's do that. This runs after_create.
  def follow_steve
    return if username == "steve"
    steve = User.first(:username => 'steve')
    return if steve.nil?

    follow! steve
    steve.follow! self
  end

      
  def self.from_omniauth(auth)
    #binding.pry
    # here we'll try first_or_... -- if that doesn't work we'll try find_or_ ...
    user = User.find_or_initialize_by_provider_and_uid(auth[:provider], auth[:uid])
    user.username = auth.info.nickname
    # if they are trying authentication for the first time ever,
    #   the save will fail due to validation failure
    user.save
    user

  end

  def password_required?
    super && provider.blank?
  end

  def self.new_with_session(params, session)

    if session["devise.user_attributes"]  
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedController
  load_and_authorize_resource
  skip_authorize_resource :only => [:following, :followers, :deleted_user] #anyone can perform these read-only actions
  require 'will_paginate/array'

  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 1)
    respond_to do |format|
      format.html
    end  
  end

  def follow
    followee = User.first(:id => params[:user][:followee])
    policy = FollowingPolicy.new(current_user)
    if policy.can_follow? followee
      current_user.follow! followee
      notice = "You're following #{followee.username} now"
    elsif policy.following_self? followee
      notice = "You can't follow yourself silly!"
    elsif policy.already_following? followee
      notice = "You're already following #{followee.username}"
    end
    redirect_to resource_path(followee), :notice=> notice
  end

  def unfollow
    followee = User.first(:id => params[:user][:followee])
    current_user.unfollow! followee
    redirect_to resource_path(followee), :notice=> "You're no longer following #{followee.username}"
  end

  def following
    @user = User.first(:username => params[:user_id])
  end

  def followers
    @user = User.first(:username => params[:user_id])
  end

  def deleted_user
    @user = DeletedUser.new
  end

  #################

  def resource
    @user ||= end_of_association_chain.find_by_username(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url email
    require 'digest/md5'
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.downcase)}"
  end
end

app/views/users/_form.html.haml
- submit_label ||= "Update"
= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
  = f.error_notification
  .inputs
    = f.input :username, :autofocus => true
    = f.input :email
  .inputs
    - pwd_options = resource.new_record? ? {} : {:hint => "Leave it blank if you don't want to change it"}
    = f.input :password, pwd_options.merge({:required => false})
    = f.input :password_confirmation, :required => false
  .inputs
    = f.input :about, :as => :text
  - unless resource.new_record?
    .inputs
      = f.input :current_password, :required => true, :hint => "We need your password to update your account."
  .actions
    = f.button :submit, submit_label, :class => "btn primary"

app/views/users/deleted_user.html.haml
%h2 This user has been deleted, sorry

app/views/users/followers.html.haml
%h1 #{resource.username}'s followers:
%ul
- resource.followers.each do |follower|
  %li
    %a{:href=> resource_path(follower)}= follower.username

app/views/users/following.html.haml
%h1 #{resource.username} is following:
%ul
- resource.following.each do |followee|
  %li
    %a{:href=> resource_path(followee)}= followee.username

app/views/users/index.html.haml
%ul
	- @users.each do |user|
		%li
			.info
				.title= user.username
			.categories
				.btn.success= link_to "Email him", mailer_path(:user => user)
= will_paginate @users

app/views/users/show.html.haml
- content_for :title do
  = "#{resource.username}'s Profile"

-content_for :sidebar do
  %section.about-user
    %img{:src => gravatar_url(resource.email)}
    - if current_user && current_user != resource
      -if current_user.following?(resource)
        = simple_form_for(resource, :url => resource_path(current_user) + '/unfollow', :method=>:post) do |f|
          = f.hidden_field :followee, :value => resource.id
          = f.button :submit, :value => "Unfollow", :class => "primary btn"
      - else
        = simple_form_for(resource, :url => resource_path(current_user) + '/follow', :method=>:post) do |f|
          = f.hidden_field :followee, :value => resource.id
          = f.button :submit, :value => "Follow", :class => "primary btn"

    - unless resource.about.blank?
      %p= resource.about
    %p
      = link_to pluralize(resource.programs.count, "Program"), user_programs_path(resource), :class => "user-programs"
    %p
      Following:
      =link_to resource.following.count, resource_path(resource) + "/following", :class => 'user-following'
    %p
      Followers:
      = link_to resource.followers.count, resource_path(resource) + "/followers", :class => 'user-followers'
    %hr
    - if can? :update, resource
      = link_to "Change My Settings", edit_registration_path(resource), :class => "btn success"


- unless @user.questions.empty?
  %section.user-questions
    .heading
      %h3= pluralize(@user.questions.count, "Question")
    %ul
      - @user.questions.each do |question|
        %li
          .title
            = link_to question.title, question_path(question)
          .meta
            asked #{question.created_at.strftime("%b %e, %l:%M %p")}

- unless @user.answers.empty?
  %section.user-answers
    .heading
      %h3= pluralize(@user.answers.count, "Answer")
    %ul
      - @user.answers.each do |answer|
        %li
          .description
            = answer.description.truncate(100)
          .meta
            = link_to("View Answer", answer.question)