config/routes.rb
HacketyHackCom::Application.routes.draw do

  get "users/index"

  match 'mailer' => 'mailer#new', :as => 'mailer', :via => :get
  match 'mailer' => 'mailer#create', :as => 'mailer', :via => :post
  get 'users/deleted_user', :to => 'users#deleted_user'

  resources :lessons, :only => [:index, :show]

  resources :questions do
    resources :answers
  end

  resources :blog, :controller => "blog" do
    match "admin", :on => :collection, :controller => "blog", :action => "admin"
  end

  get "/downloads/latest/:platform", :to => "static#download", :as => 'downloads'
  get "/downloads/latest", :to => "static#download", :as => 'download'
  match "/download" => redirect("/downloads/latest")

  scope '/support', :as => 'support' do
    resources :questions, :controller => 'questions' do
      resources :answers
    end
  end

  constraints(ApiConstraint) do
    match '/' => 'static#api_root'
    match '/versions/newest' => 'static#newest_version', :as => "newest_version"
    scope :module => "Api" do
      resources :rels, :only => [:index, :show]
        resources :programs
    end
  end

  resources :programs, :only => [:index, :show]

  devise_for :users
  devise_scope :user do
    get "login" => "devise/sessions#new", :as => "login"
    get "logout" => "devise/sessions#destroy", :as => "logout"
  end

  resources :users, :constraints => { :id => /.*/ }, :only => :show do
    get "following" => "users#following", :as => :following
    get "followers" => "users#followers", :as => :followers
    post "follow" => "users#follow", :as => :follow
    post "unfollow" => "users#unfollow", :as => :unfollow

    resources :programs
  end

  # match ':user_id/:slug', :to => "programs#show", :as => :program

  match 'faq' => 'static#faq'
  root :to => "static#root"

end

app/views/shared/_ask.html.haml
%section.ask
  %h2 Have A Question?
  %p Ask away! No question is too big or too small.
  - if current_user
    - if @support
      = link_to "Ask a Question", new_question_path(:support => true), :class => "btn success"
    - else
      = link_to "Ask a Question", new_question_path, :class => "btn success"
  - else
    %p Log in to ask a question
    = link_to "Log In", login_path, :class => "btn success"

app/views/shared/_lessons.html.haml
%section.lessons
  %h2 Want to help?
  %p Help us create new lessons, or update existing ones. Check out the Lessons project on Github below:
  = link_to "Hackety Hack Lessons on Github", "https://github.com/hacketyhack/hackety_hack-lessons"

app/views/shared/_questions_blurb.html.haml
%section.support
  %h2 Ruby Questions
  %p Programming problem got you stumped? Find Ruby a bit confusing? Check out the #{link_to "questions section", questions_path}.

app/views/shared/_recent.html.haml
%section.recent
  %h2 Recent Posts
  %ul
    - BlogPost.sort("created_at DESC").limit(5).each do |post|
      %li
        = link_to post.title, blog_path(post)

app/views/shared/_support_blurb.html.haml
%section.support
  %h2 Support
  %p Having a problem running Hackety Hack? Found a bug? Check out the #{link_to "support section", support_questions_path}