config/routes.rb
HacketyHackCom::Application.routes.draw do

  get "users/index"

  match 'mailer' => 'mailer#new', :as => 'mailer', :via => :get
  match 'mailer' => 'mailer#create', :as => 'mailer', :via => :post
  get 'users/deleted_user', :to => 'users#deleted_user'

  resources :lessons, :only => [:index, :show]

  resources :questions do
    resources :answers
  end

  resources :blog, :controller => "blog" do
    match "admin", :on => :collection, :controller => "blog", :action => "admin"
  end

  get "/downloads/latest/:platform", :to => "static#download", :as => 'downloads'
  get "/downloads/latest", :to => "static#download", :as => 'download'
  match "/download" => redirect("/downloads/latest")

  scope '/support', :as => 'support' do
    resources :questions, :controller => 'questions' do
      resources :answers
    end
  end

  constraints(ApiConstraint) do
    match '/' => 'static#api_root'
    match '/versions/newest' => 'static#newest_version', :as => "newest_version"
    scope :module => "Api" do
      resources :rels, :only => [:index, :show]
        resources :programs
    end
  end

  resources :programs, :only => [:index, :show]

  devise_for :users
  devise_scope :user do
    get "login" => "devise/sessions#new", :as => "login"
    get "logout" => "devise/sessions#destroy", :as => "logout"
  end

  resources :users, :constraints => { :id => /.*/ }, :only => :show do
    get "following" => "users#following", :as => :following
    get "followers" => "users#followers", :as => :followers
    post "follow" => "users#follow", :as => :follow
    post "unfollow" => "users#unfollow", :as => :unfollow

    resources :programs
  end

  # match ':user_id/:slug', :to => "programs#show", :as => :program

  match 'faq' => 'static#faq'
  root :to => "static#root"

end

app/models/answer.rb
class Answer
  include MongoMapper::Document

  key :description, String
  timestamps!

  validates_presence_of :description

  belongs_to :question
  belongs_to :user

end

app/controllers/answers_controller.rb
class AnswersController < InheritedController
  load_and_authorize_resource

  belongs_to :question

  def create
    @answer = Answer.create params[:answer]
    @answer.question = @question
    @answer.user = current_user

    Notification.new_answer(@question).deliver

    create!(:notice => "Answer Posted!"){ question_url(params[:question_id]) }
  end

  def update
    # inherited resorces (gem) magic
    super do |format|
      format.html { redirect_to question_url(resource.question) }
    end
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
= simple_form_for(resource, :url => @form_url) do |f|
  = render 'form_content', :f => f

app/views/answers/_form_content.html.haml
= f.error_notification

.inputs
  = f.input :description, :as => :text, :label => "Answer",
  :hint => "You can format your input with <a href=\"http://daringfireball.net/projects/markdown/\">Markdown</a>".html_safe

.actions
  = f.button :submit, :value => "Post Answer", :class => "primary btn"

app/views/answers/_list.html.haml
%li.answer{:class => list.id == @question.solution_id && 'selected-answer'}
  - if list.user
    .meta
      #{link_to list.user.username, user_path(list.user)} says
  .description
    :markdown
      #{list.description}

  .links
    - if can? :update, list
      = link_to 'Edit', edit_question_answer_path(@question, list)
    - if can? :destroy, list
      = link_to 'Delete', question_answer_path(@question, list), :confirm => 'Are you sure?', :method => :delete

  - if can?(:update, @question) && (@question.solution_id != list.id)
    .choose
      = simple_form_for(@question, :url => question_path(@question)) do |f|
        = f.hidden_field :solution_id, :value => list.id
        = f.button :submit, :value => "This answers my question!", :class => "primary btn"

app/views/answers/_short_answer.html.haml
= simple_form_for(@answer, :url => question_answers_path(@question)) do |f|
  = render 'answers/form_content', :f => f

app/views/answers/edit.html.haml
- content_for :title do
  = "Editing your answer"

= render 'form'

app/views/answers/index.html.haml
- content_for :title do
  Answers

- content_for :links do
  - if can? :create, Answer
    = link_to "New answer", new_resource_path

%ul.answers
  = render :partial => "list", :collection => collection

app/views/answers/new.html.haml
- content_for :title do
  New answer

= render 'form'

app/views/answers/show.html.haml
- content_for :title do
  = resource

- content_for :links do
  - if can? :update, resource
    = link_to 'Edit', edit_resource_path
  - if can? :destroy, resource
    = link_to 'Delete', resource_path, :confirm => 'Are you sure?', :method => :delete

%dl
  %dt Description
  %dd= resource.description
  %dt User
  %dd= resource.user